root-dir: s3://ons-web-page/publishing/2017-01-23/master/
cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_ACCESS_KEY}
      instanceProfile: true
    region:
      static: eu-west-1

kafka:
  zookeeper:
    connect: localhost:9092
  topic: dp.enrichment
  message-key: si.key
  auto-start: false
  consumers: 4
spring:
  main:
     web-environment: false
     banner-mode: log
  kafka:
    consumer:
      group-id: dpEnrichedPublishedDocument
      enable-auto-commit: true
      auto-commit-interval: 100
#      max-poll-interval: 300000
      max-poll-records: 10
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      batch-size: 16384
      buffer-memory: 33554432
      retries: 0
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  application:
    name: EnrichSearch
  autoconfigure:
    exclude: org.springframework.cloud.aws.autoconfigure.mail.MailSenderAutoConfiguration
  jmx:
    enabled: false
  activemq:
    in-memory: false
  artemis:
    embedded:
      enabled: false

elasticsearch:
#  cluster-name: ONSCluster
  ignore-cluster-name: true
  inet-addresses:
        -
          host: localhost
          port: 9300
